sudo: required

services:
  - docker

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_script:
  - sudo chmod +x /usr/local/bin/sbt

before_install:
  - docker run -d -it -p 6650:6650 -p 8080:8080 -v $PWD/data:/pulsar/data apachepulsar/pulsar:2.4.1 bin/pulsar standalone --advertised-address 127.0.0.1

scala:
- 2.12.9

script:
- sbt clean test

jdk:
- oraclejdk8
